"""phase 4.5: wholesale applications, quotes, line items, wholesale orders, b2b product fields

Revision ID: 10eab7b3d58c
Revises: 4b1d2e3f4050
Create Date: 2026-06-26 03:02:31.267411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '10eab7b3d58c'
down_revision: Union[str, Sequence[str], None] = '4b1d2e3f4050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='submitted', nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('shipping_cost', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    op.create_index(op.f('ix_quotes_user_id'), 'quotes', ['user_id'], unique=False)
    op.create_table('wholesale_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wholesale_applications_id'), 'wholesale_applications', ['id'], unique=False)
    op.create_index(op.f('ix_wholesale_applications_user_id'), 'wholesale_applications', ['user_id'], unique=False)
    op.create_table('wholesale_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='awaiting_payment', nullable=False),
    sa.Column('payment_status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('shipping_carrier', sa.String(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wholesale_orders_id'), 'wholesale_orders', ['id'], unique=False)
    op.create_index(op.f('ix_wholesale_orders_quote_id'), 'wholesale_orders', ['quote_id'], unique=True)
    op.create_index(op.f('ix_wholesale_orders_user_id'), 'wholesale_orders', ['user_id'], unique=False)
    op.create_table('quote_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_line_items_id'), 'quote_line_items', ['id'], unique=False)
    op.create_index(op.f('ix_quote_line_items_quote_id'), 'quote_line_items', ['quote_id'], unique=False)
    op.add_column('products', sa.Column('b2b_only', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('b2b_min_order_qty', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'b2b_min_order_qty')
    op.drop_column('products', 'b2b_only')
    op.drop_index(op.f('ix_quote_line_items_quote_id'), table_name='quote_line_items')
    op.drop_index(op.f('ix_quote_line_items_id'), table_name='quote_line_items')
    op.drop_table('quote_line_items')
    op.drop_index(op.f('ix_wholesale_orders_user_id'), table_name='wholesale_orders')
    op.drop_index(op.f('ix_wholesale_orders_quote_id'), table_name='wholesale_orders')
    op.drop_index(op.f('ix_wholesale_orders_id'), table_name='wholesale_orders')
    op.drop_table('wholesale_orders')
    op.drop_index(op.f('ix_wholesale_applications_user_id'), table_name='wholesale_applications')
    op.drop_index(op.f('ix_wholesale_applications_id'), table_name='wholesale_applications')
    op.drop_table('wholesale_applications')
    op.drop_index(op.f('ix_quotes_user_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
