"""phase 4: admin ImportJob table, coupon starts_at/ends_at/per_user_limit/is_active,
chatbot_logs.resolved_at, products.is_active

PLAN 4.4 / 4.6 / 4.7: build the DB schema for the admin work the front-end
will need. The migration is hand-written (rather than autogenerated) so
the column order in each table matches the new model definitions and
existing rows are upgraded safely:

- coupons.valid_from -> starts_at (kept around as a back-compat shadow
  column so older code that still references it doesn't break). New
  columns ends_at, per_user_limit, is_active are added.
- chatbot_logs gets resolved_at + resolved_by_id.
- products gets is_active.
- import_jobs is a brand-new table.

Revision ID: 7a2c4d9e1f30
Revises: 19f252d4151a
Create Date: 2026-06-26 00:30:00.000000
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "7a2c4d9e1f30"
down_revision: Union[str, Sequence[str], None] = "19f252d4151a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---- coupons: valid_from -> starts_at, add ends_at/per_user_limit/is_active
    # Back-compat: keep the old valid_from column but stop reading it.
    op.add_column(
        "coupons",
        sa.Column("starts_at", sa.DateTime(), nullable=True),
    )
    op.execute("UPDATE coupons SET starts_at = valid_from;")
    op.alter_column("coupons", "starts_at", nullable=False)

    op.add_column(
        "coupons",
        sa.Column("ends_at", sa.DateTime(), nullable=True),
    )
    # If a row had valid_until set, propagate it; otherwise leave NULL.
    op.execute("UPDATE coupons SET ends_at = valid_until WHERE valid_until IS NOT NULL;")

    op.add_column(
        "coupons",
        sa.Column("per_user_limit", sa.Integer(), nullable=True),
    )
    op.add_column(
        "coupons",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
    )

    # ---- chatbot_logs: PLAN 4.7
    op.add_column(
        "chatbot_logs",
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "chatbot_logs",
        sa.Column("resolved_by_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        "chatbot_logs_resolved_by_id_fkey",
        "chatbot_logs",
        "users",
        ["resolved_by_id"],
        ["id"],
    )
    op.create_index(
        "ix_chatbot_logs_resolved_at",
        "chatbot_logs",
        ["resolved_at"],
    )

    # ---- products: PLAN 4.3 bulk-action support
    op.add_column(
        "products",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
    )
    op.create_index("ix_products_is_active", "products", ["is_active"])

    # ---- import_jobs: PLAN 4.4
    op.create_table(
        "import_jobs",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default=sa.text("'pending'"),
        ),
        sa.Column("schema_version", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column("payload", postgresql.JSONB, nullable=False),
        sa.Column("total_products", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("imported_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("would_create", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("would_update", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "categories_to_create",
            postgresql.JSONB,
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "row_errors",
            postgresql.JSONB,
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "import_errors",
            postgresql.JSONB,
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("admin_user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["admin_user_id"], ["users.id"]),
    )
    op.create_index("ix_import_jobs_id", "import_jobs", ["id"])
    op.create_index("ix_import_jobs_status", "import_jobs", ["status"])
    op.create_index("ix_import_jobs_admin_user_id", "import_jobs", ["admin_user_id"])


def downgrade() -> None:
    op.drop_index("ix_import_jobs_admin_user_id", table_name="import_jobs")
    op.drop_index("ix_import_jobs_status", table_name="import_jobs")
    op.drop_index("ix_import_jobs_id", table_name="import_jobs")
    op.drop_table("import_jobs")

    op.drop_index("ix_products_is_active", table_name="products")
    op.drop_column("products", "is_active")

    op.drop_index("ix_chatbot_logs_resolved_at", table_name="chatbot_logs")
    op.drop_constraint("chatbot_logs_resolved_by_id_fkey", "chatbot_logs", type_="foreignkey")
    op.drop_column("chatbot_logs", "resolved_by_id")
    op.drop_column("chatbot_logs", "resolved_at")

    op.drop_column("coupons", "is_active")
    op.drop_column("coupons", "per_user_limit")
    op.drop_column("coupons", "ends_at")
    op.drop_column("coupons", "starts_at")
